name: PR Approval Bypass Notifier
on:
  pull_request:
    types:
      - closed
    branches: [main, v2]
permissions:
  pull-requests: read
jobs:
  approval:
    if: false  # Disabled
    uses: bufbuild/base-workflows/.github/workflows/notify-approval-bypass.yaml@main
    secrets: inherit
