name: Publish to npm

on:
  push:
    tags: ["releases/*"]

permissions:
  contents: write
  pull-requests: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
      - name: Extract version from tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/releases/}" >> $GITHUB_ENV
      - name: Update package.json version
        run: |
          jq ".version = \"$VERSION\"" packages/protoc-gen-es/package.json > tmp.json
          mv tmp.json packages/protoc-gen-es/package.json
      - run: npm ci
      - run: npx turbo run build -F @qdrant/protoc-gen-es
      - run: cd packages/protoc-gen-es && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish Release Notes
        uses: release-drafter/release-drafter@v6
        with:
          disable-autolabeler: true
          commitish: ${{ github.ref }}
          tag: releases/$VERSION
          name: releases/$VERSION
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}